import "bootstrap/dist/css/bootstrap.min.css";

import type { Metadata } from "next";
import { NavBar } from "./components/NavBar/Navbar";
// import { Geist, Geist_Mono } from "next/font/google";

export const metadata: Metadata = {
  title: "WA Loja",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body suppressHydrationWarning>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
