import "bootstrap/dist/css/bootstrap.min.css";

import type { Metadata } from "next";
import { NavBar } from "./components/NavBar/Navbar";
import BootstrapClient from "./components/Clients/BootstrapClient";

export const metadata: Metadata = {
  title: "WA Loja",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body suppressHydrationWarning>
        <NavBar />
        {children}
        <BootstrapClient/>
      </body>
    </html>
  );
}
