import "bootstrap/dist/css/bootstrap.min.css";
import type { Metadata } from "next";
import { NavBar } from "./components/NavBar/Navbar";
import BootstrapClient from "./components/Clients/BootstrapClient";
import { ReactQueryClientProvider } from "./components/Clients/ReactQueryClient";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "WA Loja",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body suppressHydrationWarning>
        <ReactQueryClientProvider>
          <NavBar />
          {children}
          <ToastContainer />
          <BootstrapClient/>
          <ReactQueryDevtools/>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
